- hosts: app
  sudo: yes
  vars_files:
    - ../vars/common.yml
    - group_vars/all.yml
  roles:
    - ../common-roles/base
    - ../common-roles/nginx
    - ../common-roles/rbenv
    - ../common-roles/memcached
    - nginx-config

- hosts: db
  sudo: yes
  vars_files:
    - ../vars/common.yml
    - group_vars/all.yml
  roles:
    - ../common-roles/base
    - ../common-roles/mysql-server
    - mysql-server-config

- hosts: mongodb
  sudo: yes
  vars_files:
    - ../vars/common.yml
    - group_vars/all.yml
  roles:
    - ../common-roles/base
    - ../common-roles/mongodb

- hosts: cache
  sudo: yes
  vars_files:
    - ../vars/common.yml
    - group_vars/all.yml
  roles:
    - ../common-roles/base
    - ../common-roles/redis
