- hosts: app
  sudo: yes
  vars_files:
    - ../vars/common.yml
    - group_vars/all.yml
  roles:
    #- ../common-roles/base
    #- ../common-roles/nginx
    #- ../common-roles/rbenv
    #- nginx-config

- hosts: db
  sudo: yes
  vars_files:
    - ../vars/common.yml
    - group_vars/all.yml
  roles:
    - ../common-roles/base
    #- ../common-roles/mongodb
    - ../common-roles/mysql-server
