- name: create repository for packages
  copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo

- name: be sure mongodb is installed
  yum: name=mongodb-org state=latest
  tags: mongodb

- name: be sure mongodb is enabled
  command: /sbin/chkconfig mongod on
  tags: mongodb

- name: be sure mongodb is running
  command: /etc/init.d/mongod start
  tags: mongodb
