- name: create repository for packages
  copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo

- name: be sure mongodb is installed
  yum: name=mongodb-org state=latest
  tags: mongodb

- name: be sure mongod is running and enabled
  service: name=mongod state=running enabled=yes
  tags: mongodb
