- name: nginx-config | set nginx.conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify:
    - restart nginx

- name: nginx-config | set default.conf
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=0644
  notify:
    - restart nginx
